### PR TITLE
Fixed panic on unwrapping $XDG_CACHE_HOME

### PR DESCRIPTION
**Pull request by Qustio**
When the program cannot find the `$XDG_CACHE_HOME` directory in the filesystem, it previously panicked. To address this issue, I've added a fallback mechanism to use `$HOME/.cache/Iconic` when `$XDG_CACHE_HOME` is not set.
Default path for `$XDG_CACHE_HOME` is specified by the Freedesktop-basedir specification: https://specifications.freedesktop.org/basedir-spec/latest/

Also I've formatted rust sources using cargo fmt

### CODE REVIEW

**Comment by youpie** [comment]
thank you so much for this. however, can you revert the merge about the formatting. I can't easily see that way if you have added anything to the code. 

After merging I'll format the code myself, and automate it if possible because I should really be doing that as standard

**Comment by Qustio** [comment]
Done

**Comment by Qustio** [comment]
Done

**Comment by youpie** [comment]
Great, ill merge it!

**Comment by youpie** [comment]
Thank you very much for your work

**Pull request merged**
