### PR TITLE
po: Added Hindi Translation

### PR DESCRIPTION
**Pull request by Scrambled777**
Initial Hindi `hi` language translation.

### CODE REVIEW

**Comment by youpie** [comment]
Thanks for your work!!

**Comment by Scrambled777** [comment]
@youpie, Cool app mate.

Could I suggest some improvements in few strings?

> String 26
msgid "Easilly add icons on top of folders"

Typo in `Easilly`.

> String 47
msgid "Begin screen of application"

"Beginning screen of application"

> String 83
msgid "You can now temporarilly open a new folder image"

Typo in `temporarilly`

**Comment by youpie** [comment]
Oh thanks for catching. Ill fix the typos asap

**Comment by Scrambled777** [comment]
> Oh thanks for catching. Ill fix the typos asap

You are fast. Cheers.

**Pull request merged**
